### ISSUE TITLE
Handle EML and MSG files as attachments

### ISSUE THREAD

**Issue by frikky** [frikky/Shuffle-apps#113]
Make it possible to read both attachment types. These are important as they're used for Phishing handling, and we need to be able to read and convert them

Ideally, we'd get the data back in the same email format as everything else we have in the OWA app.

MSG: https://pypi.org/project/msg-parser/
EML: https://pypi.org/project/eml-parser/

**Comment by frikky** [comment]
- [ ] Test manually file downloads from Shuffle API outside shuffle with MSG files
- [ ] Download .EML files directly from protection.office.com

**Comment by azgaviperr** [comment]
Noice
