### ISSUE TITLE
Document process or add GUI element to modify App visibility/permissions

### ISSUE THREAD

**Issue by malstor** [frikky/Shuffle-apps#12]
Currently, when adding an App, as an admin, I was unable to find a reference on how to enable other users or admins to access this new app.

I can see the app listed as private, but it is not visible to other users or admins. 

One consideration would be to enable visibility to all apps for admins, or enable an element to otherwise manage permissions and visibility as part of the "Edit" app UI.

**Comment by frikky** [comment]
Thanks! I'll get this done :+1:

**Comment by frikky** [comment]
Hey! This has been added and is usable if you're the owner of the app or an admin. 

Admins are also able to see all activated apps now, while normal users can only see ones:
* shared from admins (OpenAPI)
* Created with Python
![image](https://user-images.githubusercontent.com/5719530/91481040-1ef6e900-e8a4-11ea-9db9-a2ae0d350d04.png)

**Comment by frikky** [comment]
This is now live!

**Comment by malstor** [comment]
Amazing! Thank you
