### ISSUE TITLE
Add encoding/decoding options as actions to Shuffle-tools

### ISSUE THREAD

**Issue by frikky** [frikky/Shuffle-apps#123]
E.g. Base64 to String and String to Base64

**Comment by arnydo** [comment]
I can take a look at this if no one else is yet...

**Comment by frikky** [comment]
I'd love that. Don't think anyone else picked it up in the last 30 minutes :100:

**Comment by arnydo** [comment]
Well what are they waiting for???? lol

**Comment by frikky** [comment]
Added a while back, especially for base64!
