### ISSUE TITLE
OWA App - Add option to filter by category/tag

### ISSUE THREAD

**Issue by arnydo** [frikky/Shuffle-apps#128]
Working on an enhancement for the OWA app to allow filtering email by category/tag.

**Comment by frikky** [comment]
ooh, sweet! Thinking about how to standardize this as we get into other mailboxes as well. How do you like our email format right now btw? Anything missing?

**Comment by arnydo** [comment]
I think it may be hard to to standardize this field/term as each vendor seems to have different terms for the same idea.
- Outlook: Category 
- Gmail: Label
- Apple: Flag

Regarding the overall layout of the OWA app.
I am happy with the message format and think it works well. The only thing missing was the ability to filter by tags/categories.

**Comment by arnydo** [comment]
I think it would also be beneficial to be able to add a category/tag.

Would you like to see that as a separate function or included in another.

I think it may need to be a separate function.

**Comment by arnydo** [comment]
Added a new action `add_category` and tests so far have been successful.

![image](https://user-images.githubusercontent.com/11653079/113609250-84b90980-9619-11eb-807c-067c9d008639.png)
![image](https://user-images.githubusercontent.com/11653079/113609358-a4503200-9619-11eb-9f92-b93ae163e1f6.png)

**Comment by frikky** [comment]
Closing as you did a good job on this one.
