### ISSUE TITLE
[OWA] Fail with empty Category

### ISSUE THREAD

**Issue by azgaviperr** [frikky/Shuffle-apps#139]
Got an issue trying the new OWA APP

![image](https://user-images.githubusercontent.com/7451354/114373698-25ac4500-9b83-11eb-8c2c-dd05d886d674.png)

![image](https://user-images.githubusercontent.com/7451354/114373760-365cbb00-9b83-11eb-8e5a-27bcf6f2b561.png)

**Comment by frikky** [comment]
Looks like the app may not have finished building the container, but still updated the frontend. Could you try to Force Update the apps?

**Comment by arnydo** [comment]
I just tested on my end to confirm the `category` field can be left blank and it completed successfully. I think Frikky is correct. 
![image](https://user-images.githubusercontent.com/11653079/114400006-86318700-9b6f-11eb-849f-ba42fc3fd136.png)
![image](https://user-images.githubusercontent.com/11653079/114400040-90538580-9b6f-11eb-8072-821ea73e0323.png)

**Comment by azgaviperr** [comment]
Issue can be closed, forcing the app update did the trick
