### ISSUE TITLE
Create Microsoft Compliance Center app  

### ISSUE THREAD

**Issue by frikky** [frikky/Shuffle-apps#152]
- Sign up for Azure (Office365) demo account
- Go to https://protection.office.com
- Create app to get and change alerts at https://protection.office.com/viewalerts using Oauth2
- Create more actions to get the data at https://protection.office.com/airinvestigation

**Comment by azgaviperr** [comment]
This is a must have ^^

**Comment by frikky** [comment]
- [x ] Security
- [ ] Microsoft Teams
- [ ] Compliance
- [ ] Identity and Access (IAM)
- [ ] Windows Updates
- [ ] Applications
- [ ] 
- [ ] Excel
- [ ] People
- [ ] Search

**Comment by azgaviperr** [comment]
Any Preview version, really waiting to put my breaking hands on that ;)
![image](https://user-images.githubusercontent.com/7451354/117077656-cf24c780-ad38-11eb-9d7a-d814ac7be885.png)
