### ISSUE TITLE
TheHive Delete Alert Artifact

### ISSUE THREAD

**Issue by pandvan** [frikky/Shuffle-apps#164]
The new action _Delete alert artifact_ introduced with TheHive v1.1.1 doesn't work because it is intended to be used only with TheHive v4 by upstream API.

When the App make the connection to TheHive via TheHive4py it doesn't specify the version and by default v3 is assumed, as stated in the API docs: https://thehive-project.github.io/TheHive4py/reference/api/#thehive4py.api.TheHiveApi.__init__

In fact, running the action leads to the following error:
```
An error occured during execution: This function is available in TheHive 4 ONLY
```

**Comment by frikky** [comment]
Thanks for the report! This is definitely something we'll need to fix - probably by making it TheHive4 IF an organization is defined

**Comment by frikky** [comment]
Update: this has been fixed! :)

**Comment by pandvan** [comment]
Hi @frikky, thanks for the fix.
The original problem is now gone but the action actually do nothing.
Just created a brand new workflow with only 1 node to execute this action.

From the logs of app container I can see
```
2021-06-22 16:08:23,546 - TheHive - INFO:Sending starting action result (EXECUTING)
2021-06-22 16:08:23,546 - TheHive - INFO:AFTER FULLEXEC stream result (init)
2021-06-22 16:08:23,547 - TheHive - DEBUG:Executed Test-262e9f06-6ca2-4c72-a920-b5d84dc2f101
2021-06-22 16:08:23,547 - TheHive - INFO:Before last stream result
2021-06-22 16:08:23,603 - TheHive - INFO:Result: 200
Normal execution. Action is a string.

Fixing branch return as object -> string
No authentication specified!
Normal parsing (not looping)
Normal parsing (not looping)
Normal parsing (not looping)
Normal parsing (not looping)
CHECKING multi execution list!
OUTER VALUE:
Returned with newparams of length 1
[INFO] Running normal execution


[INFO] Returned from execution with types <class 'str'>
[INFO] Handling return as string of length 0
[INFO] POST NEWRES RESULT!
```

and no incoming requests come to the TheHive.
The output of the node is empty as well.

**Comment by frikky** [comment]
ooh - yep, should probably do something about that. 

Before then though, could you try adding it with the OpenAPI app? It's a workaround, but we'll eventually end up making all our apps this way.

1. Find TheHive OpenAPI app under /apps
![image](https://user-images.githubusercontent.com/5719530/122963892-ff770280-d386-11eb-9b38-2348c606a40e.png)

2. Scroll down and click "New action". Make this one
![image](https://user-images.githubusercontent.com/5719530/122963954-10c00f00-d387-11eb-9401-b2b20e341f1d.png)
![image](https://user-images.githubusercontent.com/5719530/122963987-187fb380-d387-11eb-958a-1b72d7273975.png)

3. Hit save!

The app should now be available in your Workflow UI too. You'll need to re authenticate it, as it's not the same one though

**Comment by frikky** [comment]
@pandvan
