### ISSUE TITLE
IOC File parsing wrong detection

### ISSUE THREAD

**Issue by Lazarusprogrammierer** [frikky/Shuffle-apps#188]
**Describe the bug**
If you use the shuffle tool with parsing ioc file, it has problems to detect the last two lines. fourth line is a domain, it becomes detected as URL and domain. the problem of the URL is: 
The SHA256 (last line) gets included into the URL

**Screenshots**
![image](https://user-images.githubusercontent.com/12913114/130455119-6c4a6743-4f9e-47d3-afe2-2119bc8992d4.png)
![image](https://user-images.githubusercontent.com/12913114/130455170-0001447f-eb22-46d4-ba39-cd1fe4206706.png)

**To Reproduce**
1. create file with IOC (the URL has to be above SHA256 code)
2. upload it to the file manager in shuffle
3. copy the ID of the file
4. paste it into a shuffle tool - parse file IOC
5. execute and show its list
6.  get the URL once as a domain and once as URL with the Hash on it
...

**Expected behavior**
The URL shouldn't get split as a domain and as a URL. Also the SHA shouldn't be in the URL. No possibility to prevent that by a semicolon or something similar, yet.

**Comment by frikky** [comment]
Hey! Thanks for the detailed report - I Transferred the issue over to shuffle-apps for better prioritization

**Comment by frikky** [comment]
Assigned this to you @dhaval055 as it may fit well with what's being built for EML and MSG files as well. As for the issue, it's been discussed further here:

https://ptb.discord.com/channels/747075026288902237/747813673577218063/877884221014806538

The issues are essentially with [IOC-finder's Regexes for URL's](https://github.com/fhightower/ioc-finder) (not handling newline well), as well as the "find IOC's in file" issue.

**Comment by dhaval055** [comment]
Hey, upgrading [ioc_finder](https://pypi.org/project/ioc-finder/6.0.1/) to version 6.0.1 should fix this issue (current version used in shuffle-tools is 5.0.1).

**Comment by frikky** [comment]
@Lazarusprogrammierer we've bumped the version on the official app. Please force update:

https://shuffler.io/docs/apps#updating_apps_remotely
