### ISSUE TITLE
hashlookup.circl.lu in Shuffle

### ISSUE THREAD

**Issue by adulau** [frikky/Shuffle-apps#199]
CIRCL offers a free and best-effort API to lookup hashes called [hashlookup](https://hashlookup.circl.lu/) from known sources such as NSRL. There is an OpenAPI interface. It might be useful for Shuffle users.

**Comment by frikky** [comment]
Thanks for the suggestion @adulau

Looks like @shalin24999 ran the generation and export through Shuffle, and copied it over to our OpenAPI repository - thanks! We'll release it on https://shuffler.io soon as well, making it more searchable, and link it back to you guys :+1:
