### ISSUE TITLE
Creation of a PatrtOwl app

### ISSUE THREAD

**Issue by MaKyOtOx** [frikky/Shuffle-apps#2]
Hello,

It could be great to have a [PatrOwl](https://github.com/Patrowl/PatrowlManager) in the available apps! API definitions are available [here](https://github.com/Patrowl/PatrowlDocs/tree/master/api). I would be pleased to help in integration.

Thanks!

Cheers,
Nicolas

**Comment by frikky** [comment]
Hey! Shuffle is capable of grabbing OpenAPI, which it seems they have defined (at least a little bit).

That means the app in practice already exists. Try going to https://shuffler.io/apps and click "Create from OpenAPI"! 

I see now that merging apps would be very useful, as PartOwl has multiple different OpenAPI definitions

**Comment by frikky** [comment]
Released them here finally: 
https://shuffler.io/apps/12ef1a444a6c57bd8ccee6856cd5cc86
https://shuffler.io/apps/3e5dfb813ba8aeeccee3bea3cd511e41

We should do something together with this ;)

**Comment by MaKyOtOx** [comment]
Wouaw ! Greaaaaat :)
