### ISSUE TITLE
Fix search for TheHive

### ISSUE THREAD

**Issue by frikky** [frikky/Shuffle-apps#20]
search_alerts
search_cases

These should be tested properly and have more capabilities than just searching the title.

RE: Chat with @lusynda on Discord.

**Comment by mluhta** [comment]
I could implement this. I would do it using TheHive's query "language" which enables advanced searches, the user could then pass a JSON string to the search. That would be the easiest way to do this.

For example, the user could pass the following JSON string to the search node (all cases/alerts between 1.9. - 30.9.):
```json
{"_and":[{"_between":{"_field":"createdAt","_from":1598907600000,"_to":1601499599999}}]}
```

Should I create new methods for the query (search_alerts_query for example), or change the existing ones (search_alerts, search_cases)?

**Comment by frikky** [comment]
Hey!

This seems like a fine idea. You can bump the version to 1.1.0 (in api.yaml) and use the same functions :fire: 

Thanks

**Comment by felipee07** [comment]
#56 This PR should add this ability.

**Comment by frikky** [comment]
Thanks @felipee07. Seems to work!
