### ISSUE TITLE
Add timestamp comparison action

### ISSUE THREAD

**Issue by frikky** [frikky/Shuffle-apps#77]
Add a way of comparing strings as timestamps. 

Fields: 
* Value 1
* Comparison (larger than / equal / less than..)
* Number (1,2,3,4)
* Specification (seconds/minutes/hours/days etc)
* Value 2

This wouldn't necessarily feel super good right now, but does the job for now. Should make a better "custom" GUI for it for later.

Alternative: make this possible with conditions.

**Comment by pemontto** [comment]
Would be useful to have a current time macro/function and ability to do some date math:

- `time.now()` - current local time
- `utc.now()` - current UTC time
- date math - `utc.now() - date("5 hours ago")`

This could be used for scheduled workflows, e.g. run every 5 hours find events updated within the last 5 hrs

**Comment by frikky** [comment]
@synack is working on this and will probably have something ready soon :fire:

**Comment by pemontto** [comment]
Awesome, one glaring omission from the above are of course functions to parse and format datetimes to/from strings!

**Comment by frikky** [comment]
Hey @pemontto any update? Could we get a pull request? ;)

**Comment by frikky** [comment]
Suggestion from @pemontto in discord - create a transformer of sorts: strftime($.alert_date, "%s")

This can be applied to a lot of things

**Comment by frikky** [comment]
This has been added to Shuffle Tools!
